"""Add line_start and line_end to code_quality_issues

Revision ID: 21d5065019f1
Revises: f70a01b6b284
Create Date: 2025-06-26 10:47:29.163643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d5065019f1'
down_revision: Union[str, None] = 'f70a01b6b284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_quality_issues', sa.Column('line_start', sa.Integer(), nullable=True))
    op.add_column('code_quality_issues', sa.Column('line_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_quality_issues', 'line_end')
    op.drop_column('code_quality_issues', 'line_start')
    # ### end Alembic commands ###
