"""add login and github_id to users

Revision ID: 75c2410d2431
Revises: 2ea5db409268
Create Date: 2025-06-25 19:36:19.287414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c2410d2431'
down_revision: Union[str, None] = '2ea5db409268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=True))
    op.add_column('users', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_column('users', 'type')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
