"""add status and error_message to webhook_events

Revision ID: 7f0fb5d06f2c
Revises: 75c2410d2431
Create Date: 2025-06-25 20:59:10.494512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0fb5d06f2c'
down_revision: Union[str, None] = '75c2410d2431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('status', sa.String(), nullable=True))
    op.add_column('webhook_events', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'error_message')
    op.drop_column('webhook_events', 'status')
    # ### end Alembic commands ###
