"""Add github_id to Repository

Revision ID: a36c6969a86b
Revises: b4b0295fad18
Create Date: 2025-06-25 14:48:51.163835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36c6969a86b'
down_revision: Union[str, None] = 'b4b0295fad18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'repositories', ['github_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='unique')
    op.drop_column('repositories', 'github_id')
    # ### end Alembic commands ###
