"""Revamp schema for CodeAnt-style platform

Revision ID: b9623e99a176
Revises: 645882d7ff17
Create Date: 2025-06-25 04:46:29.951851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9623e99a176'
down_revision: Union[str, None] = '645882d7ff17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('maintainability_index', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['pr_files.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('likelihood', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cwe', sa.String(), nullable=True),
    sa.Column('owasp', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('code_example_bad', sa.Text(), nullable=True),
    sa.Column('code_example_good', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['pr_files.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('pr_files', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_pr_files_id'), table_name='pr_files')
    op.drop_column('pr_files', 'created_at')
    op.alter_column('pull_request_analysis_history', 'commit_sha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pull_request_analysis_history', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_pull_request_analysis_history_id'), table_name='pull_request_analysis_history')
    op.add_column('pull_request_reviews', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.alter_column('pull_request_reviews', 'reviewer_login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pull_request_reviews', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pull_request_reviews', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_pull_request_reviews_id'), table_name='pull_request_reviews')
    op.create_foreign_key(None, 'pull_request_reviews', 'users', ['reviewer_id'], ['id'])
    op.alter_column('repositories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_constraint(op.f('repositories_github_id_key'), 'repositories', type_='unique')
    op.drop_column('repositories', 'updated_at')
    op.drop_column('repositories', 'github_updated_at')
    op.drop_column('repositories', 'forks')
    op.drop_column('repositories', 'webhook_id')
    op.drop_column('repositories', 'archived')
    op.drop_column('repositories', 'url')
    op.drop_column('repositories', 'language')
    op.drop_column('repositories', 'stars')
    op.drop_column('repositories', 'description')
    op.drop_column('repositories', 'webhook_active')
    op.drop_column('repositories', 'github_created_at')
    op.drop_column('repositories', 'last_imported_at')
    op.drop_column('repositories', 'open_issues')
    op.drop_column('repositories', 'github_id')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'github_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('repositories', sa.Column('github_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('open_issues', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('last_imported_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('github_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('webhook_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('repositories', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('webhook_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('forks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('github_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('repositories_github_id_key'), 'repositories', ['github_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.alter_column('repositories', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'pull_request_reviews', type_='foreignkey')
    op.create_index(op.f('ix_pull_request_reviews_id'), 'pull_request_reviews', ['id'], unique=False)
    op.alter_column('pull_request_reviews', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pull_request_reviews', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pull_request_reviews', 'reviewer_login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('pull_request_reviews', 'reviewer_id')
    op.create_index(op.f('ix_pull_request_analysis_history_id'), 'pull_request_analysis_history', ['id'], unique=False)
    op.alter_column('pull_request_analysis_history', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('pull_request_analysis_history', 'commit_sha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('pr_files', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_pr_files_id'), 'pr_files', ['id'], unique=False)
    op.alter_column('pr_files', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('security_findings')
    op.drop_table('code_quality_issues')
    op.drop_table('pr_comments')
    # ### end Alembic commands ###
