"""sync_schema_with_current_models

Revision ID: f30704a9292f
Revises: 048e479f1b4a
Create Date: 2025-10-25 03:39:35.255590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f30704a9292f'
down_revision: Union[str, None] = '048e479f1b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_findings', 'detected_at')
    
    # Handle github_id conversion from VARCHAR to INTEGER with proper casting
    op.execute("UPDATE users SET github_id = NULL WHERE github_id = '' OR github_id IS NULL OR github_id !~ '^[0-9]+$'")
    op.alter_column('users', 'github_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='github_id::integer')
    
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'slack_webhook_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slack_webhook_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'github_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('security_findings', sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
