"""add code quality issues table

Revision ID: f70a01b6b284
Revises: f7cd7842fecd
Create Date: 2025-06-26 01:23:00.672229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f70a01b6b284'
down_revision: Union[str, None] = 'f7cd7842fecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_findings')
    op.drop_table('sca_findings')
    op.add_column('code_quality_issues', sa.Column('path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_quality_issues', 'path')
    op.create_table('sca_findings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vulnerability_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('sca_findings_pull_request_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('sca_findings_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sca_findings_pkey'))
    )
    op.create_table('secret_findings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secret_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['pr_files.id'], name=op.f('secret_findings_file_id_fkey')),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('secret_findings_pull_request_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('secret_findings_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('secret_findings_pkey'))
    )
    # ### end Alembic commands ###
