"""Add ON DELETE CASCADE to security_findings.file_id

Revision ID: fd843e6851e5
Revises: 80788ff9e57b
Create Date: 2025-06-27 04:21:33.052362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd843e6851e5'
down_revision: Union[str, None] = '80788ff9e57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sca_findings')
    op.drop_table('secret_findings')
    op.drop_table('infra_findings')
    op.drop_constraint(op.f('security_findings_file_id_fkey'), 'security_findings', type_='foreignkey')
    op.create_foreign_key(None, 'security_findings', 'pr_files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('security_findings_file_id_fkey'), 'security_findings', type_='foreignkey')
    op.create_foreign_key(op.f('security_findings_file_id_fkey'), 'security_findings', 'pr_files', ['file_id'], ['id'])
    op.create_table('infra_findings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['pr_files.id'], name=op.f('infra_findings_file_id_fkey')),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('infra_findings_pull_request_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('infra_findings_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('infra_findings_pkey'))
    )
    op.create_table('secret_findings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secret_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['pr_files.id'], name=op.f('secret_findings_file_id_fkey')),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('secret_findings_pull_request_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('secret_findings_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('secret_findings_pkey'))
    )
    op.create_table('sca_findings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vulnerability_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('sca_findings_pull_request_id_fkey')),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('sca_findings_repo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sca_findings_pkey'))
    )
    # ### end Alembic commands ###
